### ISSUE TITLE
i try it to fmx android delphi 11

### ISSUE THREAD

**Issue by okbach** [TetrisSQC/Galcon#1]
I see your work is great thanks .
I have tried to adapt the project for fmx
To build the game for the Android platform
made progress. But I hit a wall
When I found some variables and functions in a game from Winapi.Windows.pas library 
like 

```
var
PFD: pixelformatdescriptor;
RC: HGLRC;
RandSeed := GetTickCount;
....and other
msg Error : UMain.pas(353): E2003 Undeclared identifier: 'pixelformatdescriptor'

```
I couldn't find an alternative
Could it be that I missed something?
Thank you

**Comment by TetrisSQC** [comment]
This require some refractoring. This attached unit contain a screen which draws the output in a memory pointer. 

To draw it you could use

FGameDisplay.Map(TMapAccess.Write, Data);
    for y := 0 to Game.Screen.Height - 1 do
      move(Game.Screen.Scanline(y)^, Data.GetScanline(y)^,
        Game.Screen.Width * 4);
    FGameDisplay.Unmap(Data);


Mit freundlichen Grüßen/Best Regards/Ystävällisin terveisin/商祈

Dipl. Ing. Christian Hackbart
Schubertstraße 23
99096 Erfurt/Germany
E-Mail:  ***@***.*** ***@***.***>
Internet:  http://www.dvbviewer.com <http://www.dvbviewer.com/>

**Comment by okbach** [comment]
Thanks it was helpful
